Feat/vitest
fintoc-com/slach-vue pull request #11
Opened 2023-01-09 17:36 UTC by oerlandsen

# [Feature]: [Vitest setup]

## Description

Setup vitest and initial generic component tests.

## Requirements

None.

## Additional changes

None.

2023-01-09 20:44 UTC, cdaguirre reviewed
Buena Oscar! Te deje un par de comentarios sobre un test, pero es extendible al resto de los componentes genéricos. 

Otra cosa, trata de order un poco más los commits. Para que quede un historía más fácil de leer. 
Por ejemplo, tienes 2 commits con el mismo nombre, eso se podría reemplazar por el mismo commit con un ammend. Sería ideal también, ir subiendo el código siembre con el linter correcto, par ano tener que agregar ruido en los commits como el commit `fix: linter`  final.

2023-01-09 20:44 UTC, cdaguirre commented on vite.config.ts
> +    globals: true,
porque es necesario que sea global?

2023-01-09 20:44 UTC, cdaguirre commented on src/components/__test__/GenericButton.test.ts
> +  it('renders a button with width w-full', () : void => {
Lo digo para este componente en particular, pero aplica al resto de los componentes y sus tests. Si vas a testear esta prop, creo falta el test que cuando se entrega `fullWidth: false` y comprobar que efectivamente se el estilo sea el esperado. Además, creo que si ya estas testeando las props, me parece importante testear también la prop `type` y que efectivamente se rendere el estilo que esperas según el tipo del botón entregado.

2023-01-09 20:44 UTC, cdaguirre commented on src/components/__test__/GenericButton.test.ts
> +  it('renders a button', () : void => {
Así como se espera que se rendere con los estilos correctos, creo que es importante que se testee comportamiento. Para ello, puedes hacer algo como:

```js
const wrapper = mount(GenericButton);

wrapper.trigger('click');

expect(wrapper.emitted().click).toHaveLength(1)
expect(wrapper.emitted().click).toEqual('click')
```

Para más info de como se puede [testear emits](https://test-utils.vuejs.org/api/#emitted)

2023-01-09 23:09 UTC, vnazar requested changes
Buen PR Oscar!! 🚀  Lo que sí, es que creo que, como dice @cdaguirre, sería mejor que los commits tuvieran cambios que de por sí sean parte del PR final. Si te fijas, tus commits iniciales tienen cosas que no están en el PR final, como por ejemplo código comentado. Para arreglar esto, uno puede hacer fixups y autosquash ([acá](https://www.notion.so/fintoc/Fix-up-autosquash-44b5379229fb415fa710e5cbc95f3352#fbb35499c39e4d1eb38728e515dac39d) una guía) y así ordenar la historia de los commits. Cualquier duda que tengas de esto lo puedes preguntar por Slack!

2023-01-10 13:12 UTC, oerlandsen commented on vite.config.ts
> +    globals: true,
sin `  globals: true ` no me corren los tests

2023-01-11 20:00 UTC, closed without merging