fix(GenericInput): Fixed style prop
fintoc-com/slach-vue pull request #22
Opened 2023-01-18 20:26 UTC by oerlandsen

# [Fix]: [Change style prop]

## Description

Se cambió el prop de style para que la vista en donde se llama solo tenga que elegir entre dos tipos, en vez de pasarle el styling completo

## Requirements

None.

## Additional changes

None.

2023-01-20 13:17 UTC, daleal requested changes
Dejo algunos comentarios

2023-01-20 13:17 UTC, daleal commented on src/components/GenericInput.vue
> +    return 'focus:border-gray-500';
Acá creo que es bueno que el orden sea el mismo para los dos ifs. Si en el de abajo el primer if es "cuando hay un error", en el de arriba el if también debería ser para ese caso. Es más fácil de parsear mentalmente

2023-01-20 13:17 UTC, daleal commented on src/components/GenericInput.vue
> +    return 'border-yellow-300 bg-yellow-100 focus:border-yellow-400 hover:bg-yellow-200';
Encuentro medio extraño este comportamiento. Por qué cuando parto en la página el input está amarillo? No debería estar gris, amarillo cuando no existe el nombre nomás? Siento que cuando el input está vacío o cuando se está validando si existe o no existe un usuario, esto debería ser gris.

2023-01-20 13:17 UTC, daleal commented on src/components/GenericInput.vue
>  const customClass = computed(() => {
Esto no se debería llamar `customClass`, no tiene mucho sentido ese nombre en lo que estas clases están haciendo (deberían llamarse algo como `inputClasses`). Además, creo que todo esto debería ir encima de la función `updateInput` y no abajo de ella, para que leer el componente sea más fácil

2023-01-20 13:17 UTC, daleal commented on src/components/GenericInput.vue
> +    return `border-2 rounded-full px-10 py-2 w-full focus:outline-none ${inputColorClasses.value}`;
Por qué este estilo es el primario? Es el menos usado y es el más "especial" de los dos, me da la sensación de que este debería ser el secundario

2023-01-20 13:17 UTC, daleal commented on src/components/GenericInput.vue
> +  type: 'secondary',
No es como extraño que el _default_ sea usar el input secundario? Creo que el primario debería ser el que se usa en el resto de la app, y el _default_ debería ser el primario

2023-01-20 13:17 UTC, daleal commented on src/components/GenericInput.vue
> +import { InputType } from '@/types/input';
Importa los componentes al final

2023-01-20 13:17 UTC, daleal commented on src/components/GenericInput.vue
> +      disabled:bg-gray-50 disabled:text-gray-500 disabled:border-gray-200 disabled:shadow-none`;
Acá hay un par de clases que son "compartidas" entre los dos comportamientos, yo haría algo como:

```ts
const inputClasses = computed(() => {
  const baseClasses = `border-2 w-full focus:outline-none ${inputColorClasses.value}`;
  if (props.type === 'primary') {
    return `${baseClasses} rounded-full px-10 py-2`;
  }
  ...
});
```

2023-01-20 13:17 UTC, daleal commented on src/components/GenericInput.vue
> +  return '';
Incluso acá podrías poner como return las clases base nomás. En todo caso este return creo que no debería ser necesario, porque el input type solo tiene 2 valores posibles, entonces TS te debería poder dejar hacer narrowing y solo ponerte en esos dos casos

2023-01-20 21:16 UTC, oerlandsen commented on src/components/GenericInput.vue
> +    return 'border-yellow-300 bg-yellow-100 focus:border-yellow-400 hover:bg-yellow-200';
quería que fuera amarillo por el boton de abajo que es verde Lo habia puesto en rojo con los errores pero era muy agresivo por las validaciones del alias. Cuando esta mal muestra el mensaje y cuando esta bien se pone en verde.

2023-01-20 21:40 UTC, oerlandsen commented on src/components/GenericInput.vue
> +  return '';
Es necesario por el linter

2023-01-20 21:40 UTC, oerlandsen commented on src/components/GenericInput.vue
> +      disabled:bg-gray-50 disabled:text-gray-500 disabled:border-gray-200 disabled:shadow-none`;
👍

2023-01-20 21:40 UTC, oerlandsen commented on src/components/GenericInput.vue
> +import { InputType } from '@/types/input';
👍

2023-01-20 21:40 UTC, oerlandsen commented on src/components/GenericInput.vue
> +  type: 'secondary',
👍

2023-01-20 21:40 UTC, oerlandsen commented on src/components/GenericInput.vue
> +    return `border-2 rounded-full px-10 py-2 w-full focus:outline-none ${inputColorClasses.value}`;
👍

2023-01-20 21:40 UTC, oerlandsen commented on src/components/GenericInput.vue
>  const customClass = computed(() => {
👍

2023-01-20 21:40 UTC, oerlandsen commented on src/components/GenericInput.vue
> +    return 'focus:border-gray-500';
👍

2023-01-23 13:44 UTC, daleal commented on src/components/GenericInput.vue
> +  return '';
Si, lo que quiero decir es que deberías poder hacer algo así:

```ts
if (props.type === 'primary') {
  return something;
}
return someOtherThing;
```

Porque `props.type` es sí o sí `primary` o `secondary`, entonces el else es innecesario

2023-01-23 13:47 UTC, daleal approved these changes
Dejo a tu criterio si sacar o no el `return '';` sacando el `else if` innecesario, pero aparte de eso se ve bien esta PR! 🎉

2023-01-23 14:09 UTC, merged